platform:ios,9.0
use_frameworks!
target:YHDevelopFramework_Swift do

pod 'Alamofire', '~> 4.0.1'
pod 'SwiftyJSON', '~> 3.1.0'
pod 'XCGLogger', '~> 4.0.0'
pod 'KeychainAccess', '~> 3.0.0'
pod 'IQKeyboardManagerSwift', '4.0.6'
pod 'PromiseKit', '~> 4.0.3'
pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'

end
